flowchart TD;
    Start["Start"] --> Describe["Describe Instance"];
    Describe --> CheckAMI{"AMI Approved?"};
    CheckAMI -- "No" --> Terminate["Terminate Instance\nExit"] --> End;
    CheckAMI -- "Yes" --> TempIso["Temporary Isolate Instance"];
    TempIso --> Status{"Isolated? Sensor Installed?"};
    Status -- "Isolated" --> SkipIsolated["Already Isolated\nExit"] --> End;
    Status -- "Not Isolated & Sensor" --> SkipSensor["Has Sensor\nExit"] --> End;
    Status -- "Not Isolated & No Sensor" --> IsolationProcess["Isolation Process"];
    IsolationProcess --> IsolateRole["Detach Role Permissions"];
    IsolationProcess --> IsolateNetwork["Isolate Network Access"];
    IsolationProcess --> ExistsInSSM{"Exists in SSM Parameter?"};
    ExistsInSSM -- "No" --> AppendSSM["Append Entry"] --> UpdateSSM["Update SSM Param"];
    ExistsInSSM -- "Yes" --> UpdateEntry["Update Entry"] --> UpdateSSM;
    UpdateSSM --> AddPerms["Add Required Permissions"];
    AddPerms --> HasRole{"Has IAM Role?"};
    HasRole -- "Yes" --> Done;
    HasRole -- "No" --> CreateRole["Create Role"] --> CreateProfile["Create Instance Profile"] --> AddRoleProfile["Add Role to Profile"] --> AssociateRole["Associate Profile with Instance"] --> Done;
    Done --> End;
    End["End"];
